# Generated by Django 5.1 on 2024-08-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
